### ISSUE TITLE
Deploystack fails at collecting project id

### ISSUE THREAD

**Issue by rominirani** [GoogleCloudPlatform/deploystack-single-vm#7]
I am trying to use Deploystack to validate the creation of the Single VM Deploystack in a new project. The steps that I followed were:

- Open in Cloud Shell. This launches the welcome message and asks me to select a Project.
- I preferred to create a new project, so I selected [1] 
This gave the following error:

```Choose number from list.
> 1
***********************************************************************************************************************************************************************************************************************************************************************************************************************************
Creating the project
***********************************************************************************************************************************************************************************************************************************************************************************************************************************
Project IDs are immutable and can be set only during project
creation. They must start with a lowercase letter and can have
lowercase ASCII letters, digits or hyphens.
Project IDs must be between 6 and 30 characters.
Please enter a new project name to create: 
> test-romin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaf7bd3]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/deploystack.projectPrompt({0x0, 0x0})
        /root/go/pkg/mod/github.com/!google!cloud!platform/deploystack@v0.0.0-20230103175900-d283d06f26f7/ui.go:331 +0x373
github.com/GoogleCloudPlatform/deploystack.ProjectManage()
        /root/go/pkg/mod/github.com/!google!cloud!platform/deploystack@v0.0.0-20230103175900-d283d06f26f7/ui.go:288 +0x385
github.com/GoogleCloudPlatform/deploystack.Config.Process({{0xc0002afa40, 0x9}, {0xc0002afaa0, 0x9}, {0xc000272000, 0x51}, 0x1, 0x1, 0x1, 0x0, ...}, ...)
        /root/go/pkg/mod/github.com/!google!cloud!platform/deploystack@v0.0.0-20230103175900-d283d06f26f7/deploystack.go:403 +0x4ee
github.com/GoogleCloudPlatform/deploystack.(*Stack).Process(...)
        /root/go/pkg/mod/github.com/!google!cloud!platform/deploystack@v0.0.0-20230103175900-d283d06f26f7/deploystack.go:735
main.main()
        /app/ds/deploystack_exec.go:54 +0x3ec

An error occured collecting the necessary information to run your Deploystack
application. Please try again.

If the problem persists, please file an issue with the Github repo:
https://github.com/GoogleCloudPlatform/deploystack-single-vm/issues```

**Comment by tpryan** [comment]
Fixed by https://github.com/GoogleCloudPlatform/deploystack/pull/58

Will work when CloudShell updates.
